CREATE DATABASE JustDoItDb
GO

USE JustDoItDb
GO

CREATE TABLE Category (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT (NEWSEQUENTIALID()),
	[Name] NVARCHAR(50) UNIQUE NOT NULL 
)
GO

CREATE TABLE Job (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT (NEWSEQUENTIALID()),
	CategoryId UNIQUEIDENTIFIER NOT NULL REFERENCES Category(Id) ON DELETE CASCADE ON UPDATE CASCADE,

	[Name] NVARCHAR(100) NOT NULL,
	IsCompleted BIT NOT NULL DEFAULT 0,
	DueDate DATETIME NOT NULL,
)
GO